Address = "0x4827b423D03a349b7519Dda537e9A28d31ecBB48"
RPC = "https://puissant-builder.48.club"
Website = "https://www.48.club"
Description = "Puissant means powerful in French."
Contact = "puissant@48.club"